### PR TITLE
initial christchurch resbaz

### PR DESCRIPTION
**Pull request by antonangelo**
Feeling a little insecure - can someone see if this looks OK?

### CODE REVIEW

**Comment by DamienIrving** [comment]
@antonangelo Looks pretty good. I've merged it, and if you let me know the latitude / longitude coordinates of your venue I'll add Christchurch to the map on the front page of the website.

**Comment by antonangelo** [comment]
@DamienIrving thank you! Ahh, I missed one bit of cut and paste from the Dunedin files I copied from, and added the geodata to sites.geojson.

**Comment by DamienIrving** [comment]
@antonangelo I just noticed the same thing... fixing it now!

**Comment by DamienIrving** [comment]
@antonangelo Fixed!

One thing you might want to do is upload a cropped version of your background image, because at the moment it shows mainly clouds. I've given you write access to the repo so you can make that change (and any other minor tweaks) without doing a pull request, if you'd like.

**Pull request merged**
